name: opennutritracker
description: Open-Source Calories & Activity Tracker

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  pie_chart: ^5.4.0
  mock_supabase_http_client: ^0.0.1
  intl_utils: ^2.8.3
  collection: ^1.19.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  get_it: ^8.0.3
  provider: ^6.1.2
  http: any
  uuid: ^4.5.1
  json_annotation: ^4.9.0
  logging: ^1.3.0
  path_provider: ^2.1.5
  path: ^1.9.0
  bloc_test: ^9.1.0
  mocktail: ^1.0.0
  flutter_secure_storage: ^9.2.2
  cupertino_icons: ^1.0.8
  package_info_plus: ^8.1.2
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  envied: ^1.0.0
  archive: 4.0.6
  file_picker: 10.1.2

  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  app_links: ^6.4.0
  email_validator: ^2.1.17

  percent_indicator: ^4.2.4
  horizontal_picker: ^1.2.0
  table_calendar: ^3.1.3
  introduction_screen: ^3.1.14
  auto_size_text: ^3.0.0
  animated_flip_counter: ^0.3.4

  connectivity_plus: ^5.0.2

  mobile_scanner: ^6.0.2

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  supabase_flutter: ^2.9.1
  syncfusion_flutter_charts: ^30.2.7

  supabase_auth_ui: ^0.5.5
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.3.1
  firebase_crashlytics: ^4.3.10
  firebase_analytics: ^11.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # version qui Ã©vite le conflit dâ€™analyzer
  build_runner: ^2.4.13
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
  hive_generator: ^2.0.1
  envied_generator: ^1.0.0
  mockito: 5.4.4   # ðŸ‘ˆ downgrade pour rester compatible

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/ont_logo_square.png
    - assets/icon/ont_logo_square.svg
    - assets/icon/ont_logo_square_light.png
    - assets/icon/ont_banner_top.png
    - assets/icon/ont_banner_top_light.png
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-BlackItalic.ttf
          style: italic
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-BoldItalic.ttf
          style: italic
        - asset: fonts/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
          style: italic
        - asset: fonts/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins-ExtraLightItalic.ttf
          style: italic
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-Light.ttf
          style: italic
        - asset: fonts/Poppins-LightItalic.ttf
          style: italic
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-MediumItalic.ttf
          style: italic
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-SemiBoldItalic.ttf
          style: italic
        - asset: fonts/Poppins-Thin.ttf
        - asset: fonts/Poppins-ThinItalic.ttf
          style: italic

flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: true
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  adaptive_icon_background: "#ffffff"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
